# Generated by Django 5.2.5 on 2025-08-25 04:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('WAGON', 'Wagon'), ('MICRO', 'Micro'), ('HATCHBACK', 'Hatchback'), ('CROSSOVER', 'Crossover'), ('COUPE', 'Coupe'), ('COUPE SUV', 'Coupe SUV'), ('OFF-ROADER', 'Off-Roader'), ('PICK-UP', 'Pick-Up'), ('MPV', 'MPV'), ('VAN', 'Van'), ('CAMPER', 'Camper'), ('MINIVAN', 'Minivan'), ('SPORT', 'Sport'), ('CABRIOLET', 'Cabriolet'), ('ROADSTER', 'Roadster'), ('HYPER', 'Hyper'), ('MUSCLE', 'Muscle'), ('LIMOUSINE', 'Limousine'), ('OPEN WHEEL', 'Open Wheel')], default='SUV', max_length=20)),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MaxValueValidator(2025), django.core.validators.MinValueValidator(2015)])),
                ('engine_type', models.CharField(choices=[('GAS', 'Gas'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='GAS', max_length=10)),
                ('transmission', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='AUTO', max_length=10)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.carmake')),
            ],
        ),
    ]
